name: Tests
run-name: Testing the action
on:
  push:
    paths:
    - 'action.yaml'
    - '.github/workflows/tests.yaml'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          action.yaml
        sparse-checkout-cone-mode: false
    - name: Run action
      continue-on-error: true
      uses: ./
      with:
        number: 0
